export const FOOD_GROUPS = ["Vegetables", "Protein", "Grains", "Dairy", "Fruits"].sort();

// src/constants.ts
export const POSITIVE_STATES = [
    "Accomplished",
    "Alert",
    "Amazed",
    "Amused",
    "Appreciated",
    "Blissful",
    "Calm",
    "Cheerful",
    "Confident",
    "Content",
    "Creative",
    "Delighted",
    "Determined",
    "Ecstatic",
    "Elated",
    "Energetic",
    "Enthusiastic",
    "Euphoric",
    "Excited",
    "Focused",
    "Fulfilled",
    "Grateful",
    "Happy",
    "Hopeful",
    "Inspired",
    "Joyful",
    "Loved",
    "Motivated",
    "Optimistic",
    "Peaceful",
    "Playful",
    "Pleased",
    "Proud",
    "Refreshed",
    "Relaxed",
    "Relieved",
    "Satisfied",
    "Serene",
    "Thrilled",
    "Tranquil"
].sort();

export const NEGATIVE_STATES = [
    "Agitated",
    "Angry",
    "Annoyed",
    "Anxious",
    "Ashamed",
    "Bitter",
    "Bored",
    "Confused",
    "Defeated",
    "Dejected",
    "Depressed",
    "Disappointed",
    "Discouraged",
    "Disgusted",
    "Distressed",
    "Embarrassed",
    "Envious",
    "Exhausted",
    "Fearful",
    "Frustrated",
    "Guilty",
    "Helpless",
    "Hopeless",
    "Hurt",
    "Insecure",
    "Irritable",
    "Jealous",
    "Lonely",
    "Melancholy",
    "Nervous",
    "Overwhelmed",
    "Panicked",
    "Regretful",
    "Rejected",
    "Resentful",
    "Restless",
    "Sad",
    "Stressed",
    "Tired",
    "Uncomfortable",
    "Worried"
].sort();

export const POSITIVE_HABITS = [
    "Connecting with Loved Ones",
    "Healthy Eating",
    "Engaging with Hobbies",
    "Exercise",
    "Hydration",
    "Journaling",
    "Meditation",
    "Planning the Day",
    "Quality Sleep",
    "Reading"
].sort();

export const NEGATIVE_HABITS = [
    "Avoiding Responsibilities",
    "Excessive Screen Time",
    "Impulse Buying",
    "Junk Food",
    "Negative Self-Talk",
    "Oversleeping",
    "Poor Sleep",
    "Procrastination",
    "Skipping Meals",
    "Smoking"
].sort();
